# Generated by Django 3.1.1 on 2020-12-05 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201205_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fav',
            name='postss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.post'),
        ),
    ]
