# Generated by Django 3.1.1 on 2020-12-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201205_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fav',
            name='postss',
        ),
        migrations.AddField(
            model_name='fav',
            name='postss',
            field=models.ManyToManyField(related_name='favpost', to='main.Post'),
        ),
    ]
