# Generated by Django 3.1.1 on 2020-12-08 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_post_fav'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
